### ISSUE TITLE
Fix background scroll behind modal

### ISSUE THREAD

**Issue by davidindub** [davidindub/fizzbuzz#28]

**Comment by davidindub** [comment]
Changed 
```css
.modal-content {
    margin: 10% auto;
}
```
